SECRET_KEY: 'your_secret_key'
SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://username:password@localhost/ecommerce_db'
SQLALCHEMY_TRACK_MODIFICATIONS: False
JWT_SECRET_KEY: 'your_jwt_secret_key'
CACHE_TYPE: 'SimpleCache'
CACHE_DEFAULT_TIMEOUT: 300
RATELIMIT_DEFAULT: '100 per day'
